# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "master"
    paths-ignore:
      - 'issue-bot/**'
      - 'website/**'
      - 'playground-api/**'
      - 'playground-runner/**'

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-reqs"

      - name: "Tests"
        run: |
          cd e2e
          composer install --ignore-platform-reqs
          # php testPharAutoloader.php
          vendor/bin/phpunit PharTest.php
  tests-extensions:
    name: "Extension Tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        extension-name:
          - "phpstan-phpunit"
          - "phpstan-strict-rules"
          - "phpstan-mockery"
          - "phpstan-doctrine"
          - "phpstan-symfony"
          - "phpstan-php-parser"
          - "phpstan-deprecation-rules"
          - "phpdoc-parser"
          - "phpstan-nette"
          - "phpstan-dibi"
          - "phpstan-webmozart-assert"
          - "phpstan-beberlei-assert"
        static-reflection:
          - "true"
          - "false"
        exclude:
          - extension-name: "phpstan-phpunit"
            static-reflection: "true"
          - extension-name: "phpstan-symfony"
            php-version: "7.1"
            static-reflection: "false"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=256M
          extensions: soap

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-reqs"

      - name: "Extension build"
        env:
          STATIC_REFLECTION: ${{ matrix.static-reflection }}
          PHP_VERSION: ${{ matrix.php-version }}
        run: "./e2e/test-extension.sh 'https://github.com/phpstan/${{ matrix.extension-name }}.git'"

  other-tests:
    name: "Other Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-version:
          - "7.4"
          - "8.0"
        script:
          - |
            cd e2e
            git clone https://github.com/nikic/PHP-Parser.git
            cd PHP-Parser
            git checkout v3.1.5
            composer install
            ../../phpstan analyse -l 0 -c ../php-parser-baseline.neon lib
          - |
            cd e2e/react-promise
            composer install
            ../../phpstan analyse -l 8 src
          - |
            cd e2e/hoa
            composer install
            ../../phpstan analyse -l 8 src
          - |
            cd e2e/different-php-parser
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 8 test.php src
          - |
            cd e2e/different-phpdoc-parser
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 8 -a Test.php Test.php
          - |
            cd e2e/php-metrics
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 8 test.php
          - |
            cd e2e/react-bootstrap
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 8 -c phpstan.neon test.php
          - |
            cd e2e/no-autoloader
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 8 -c phpstan.neon src tests
          - |
            cd e2e/mongodb
            ../../phpstan analyse -l 8 test.php test2.php
          - |
            cd e2e/alias-event
            ../../phpstan analyse -l 8 -a alias.php test.php
          - |
            cd e2e/alias-event
            ../../phpstan analyse -l 8 -a alias.php -c staticReflection.neon test.php
          - |
            cd e2e/polyfills
            composer install
            ../../phpstan analyse -l 8 test.php
          - |
            cd e2e/symfony-event
            composer install --ignore-platform-reqs
            ../../phpstan analyse -l 2 src
          - |
            cd e2e/composer-file
            composer install
            ../../phpstan analyse -l 8 test.php
          - |
            cd e2e/php8
            ../../phpstan analyse -l 8 -c php74.neon test.php
          - |
            cd e2e/php8
            ../../phpstan analyse -l 8 -c php80.neon test.php
          - |
            cd e2e/attributes
            ../../phpstan analyse -l 8 test.php
          - |
            cd e2e/attributes
            ../../phpstan analyse -l 8 -c php80.neon test.php
          - |
            cd e2e/baseline
            ../../phpstan analyse -l 8 src/
            ../../phpstan analyse -l 8 src/ --generate-baseline
            ../../phpstan analyse -l 8 src/
            ../../phpstan analyse -l 8 src/ --generate-baseline
            ../../phpstan analyse -l 8 src/
          - |
            cd e2e/name-conflict
            composer install
            cp ../../phpstan vendor/bin/phpstan
            vendor/bin/phpstan analyse -l 8 src/
          - |
            cd e2e/excludePaths
            ../../phpstan analyse
          - |
            cd e2e/excludePaths2
            ../../phpstan analyse
          - |
            cd e2e/autoload-better-reflection
            php test.php
          - |
            cd e2e/autoloader-require
            ../../phpstan analyse
            ../../phpstan analyse tests/ClassATest.php
        include:
          - php-version: 8.0
            ini-values: memory_limit=256M
            operating-system: ubuntu-latest
            script: |
              cd e2e/union-type
              ../../phpstan analyse -l 8 test.php
          - php-version: 7.4
            ini-values: memory_limit=256M
            operating-system: ubuntu-latest
            script: |
              cd e2e/phpstorm-stubs
              composer install --ignore-platform-reqs
              ../../phpstan analyse -l 8 test.php
              vendor/bin/phpunit ExampleTest.php
          - php-version: 7.4
            ini-values: memory_limit=256M
            operating-system: windows-latest
            script: |
              cd e2e/name-conflict
              composer install
              cp ../../phpstan vendor/bin/phpstan
              vendor/bin/phpstan analyse -l 8 src/
          - php-version: 7.3
            extensions: opcache
            ini-values: memory_limit=256M, opcache.memory_consumption=128, opcache.interned_strings_buffer=8, opcache.max_accelerated_files=4000, opcache.revalidate_freq=60, opcache.fast_shutdown=1, opcache.enable_cli=1, opcache.enable=1
            operating-system: ubuntu-latest
            script: |
              cd e2e/autoloader-issue-stream-eof
              composer install
              ../../phpstan

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: " ${{ matrix.ini-values }}"
          extensions: "${{ matrix.extensions }}"

      - name: "Disable MongoDB extension"
        if: matrix.operating-system != 'windows-latest'
        run: sudo phpdismod -v ${{ matrix.php-version }} mongodb

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "${{ matrix.script }}"

  integration-tests:
    name: "Integration Tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        script:
          - |
            git clone https://github.com/sebastianbergmann/phpunit.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 9.2.3
            export COMPOSER_ROOT_VERSION=9.2.3
            composer install
            ../../../phpstan.phar analyse -l 8 -c ../phpunit.neon src tests
          - |
            git clone https://github.com/nunomaduro/larastan.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout ca98347313e20fe84daf22c08a31a550153f3be9
            composer install
            ../../../phpstan.phar analyse
          - |
            git clone https://github.com/rectorphp/rector.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 0.10.0
            cp ../rector-composer.lock composer.lock
            composer install
            ../../../phpstan.phar analyse -c ../rector.neon
          - |
            git clone https://github.com/slevomat/coding-standard.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 6.4.1
            composer install
            ../../../phpstan.phar analyse -c ../slevomat-cs.neon -l 7 SlevomatCodingStandard
            ../../../phpstan.phar analyse -c build/PHPStan/phpstan.tests.neon -l 7 tests
          - |
            git clone https://github.com/composer/composer.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 4940009f8377d06b9fb48df0cbe67193e0989830
            composer install
            composer config platform --unset && composer update
            bin/composer require --dev phpunit/phpunit:^7.5 --with-all-dependencies
            bin/composer require --dev phpstan/phpstan-phpunit
            ../../../phpstan.phar analyse -c ../composer.neon -l 5 src tests
          - |
            git clone https://github.com/pmmp/PocketMine-MP.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 0766952f3921f84fe15ef9269a262cac6b645e0f
            composer install --ignore-platform-reqs
            ../../../phpstan.phar analyse -c ../pocketmine.neon --memory-limit=2G
          - |
            git clone https://github.com/nextras/orm.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout 97e9e89ef3baf39a526bc5f098923293e21d9d86
            composer install
            ../../../phpstan.phar analyse -c .phpstan.neon

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "${{ matrix.script }}"
